[package]
name = "snurr"
version = "0.6.0-wip"
edition = "2021"
authors = ["sajox"]
description = "Read BPMN 2.0 files and run the process flow"
repository = "https://github.com/sajox/snurr"
readme = "README.md"
license = "MIT"
keywords = ["BPMN", "process"]

include = ["Cargo.toml", "LICENSE", "/src", "/examples"]

[lib]
doctest = false

[lints.rust]
unsafe_code = "forbid"

[[example]]
name = "simple"

[dependencies]
quick-xml = "0.36"
log = "0.4"
thiserror = "1.0"
hashbrown = { version = "0.15", optional = true }
rayon = { version = "1.10", optional = true }

[features]
default = ["hashbrown"]
trace = []
hashbrown = ["dep:hashbrown"]
parallel = ["dep:rayon"]


[dev-dependencies]
pretty_env_logger = "0.5"
